import { DEFAULT_HOURS } from "./constants";

export const DISPENSARIES = [
  { id: "d1", name: "Green Leaf Co.", slug: "green-leaf-co", bio: "Premium indoor cannabis, hand-trimmed and lab-tested. Cape Town's original craft cannabis collective since 2024.", tagline: "Craft Cannabis, Elevated.", address: "42 Long St, Cape Town", city: "Cape Town", province: "Western Cape", lat: -33.9249, lng: 18.4241, deliveryRadius: 15, deliveryFee: 35, minimumOrder: 100, rating: 4.8, reviews: 234, isApproved: true, isActive: true, membershipPrice: 0, membershipType: "FREE", deliveryTime: "25-35 min", ownerId: "u2", bannerUrl: "", profileUrl: "", socialLinks: { instagram: "@greenleafcpt", whatsapp: "+27821234567" }, openNow: true, featured: true, operatingHours: { ...DEFAULT_HOURS }, banking: null },
  { id: "d2", name: "Durban Poison House", slug: "durban-poison-house", bio: "Authentic Durban strains, locally grown with love. We specialize in landrace genetics from the KZN coast.", tagline: "Heritage Strains, Modern Delivery.", address: "88 Florida Rd, Durban", city: "Durban", province: "KwaZulu-Natal", lat: -29.8587, lng: 31.0218, deliveryRadius: 10, deliveryFee: 45, minimumOrder: 150, rating: 4.6, reviews: 189, isApproved: true, isActive: true, membershipPrice: 50, membershipType: "PAID", deliveryTime: "30-45 min", ownerId: "u2", bannerUrl: "", profileUrl: "", socialLinks: { instagram: "@durbanpoisonhouse", whatsapp: "+27829876543" }, openNow: true, featured: false, operatingHours: { ...DEFAULT_HOURS }, banking: null },
  { id: "d3", name: "Highveld Herbals", slug: "highveld-herbals", bio: "Johannesburg's finest selection of concentrates, edibles, and premium flower. Lab-tested, quality-assured.", tagline: "JHB's Premium Cannabis Destination.", address: "15 Melle St, Braamfontein, JHB", city: "Johannesburg", province: "Gauteng", lat: -26.1952, lng: 28.0338, deliveryRadius: 20, deliveryFee: 40, minimumOrder: 120, rating: 4.9, reviews: 312, isApproved: true, isActive: true, membershipPrice: 0, membershipType: "FREE", deliveryTime: "20-30 min", ownerId: "u2", bannerUrl: "", profileUrl: "", socialLinks: { instagram: "@highveldherbals", whatsapp: "+27831234567" }, openNow: true, featured: true, operatingHours: { ...DEFAULT_HOURS }, banking: null },
  { id: "d4", name: "Cape Kush Gardens", slug: "cape-kush-gardens", bio: "Stellenbosch greenhouse grows, organic and sustainable. Sun-grown in the Cape Winelands.", tagline: "Organic. Sustainable. Sun-Grown.", address: "7 Dorp St, Stellenbosch", city: "Stellenbosch", province: "Western Cape", lat: -33.9321, lng: 18.8602, deliveryRadius: 12, deliveryFee: 50, minimumOrder: 200, rating: 4.7, reviews: 156, isApproved: false, isActive: true, membershipPrice: 100, membershipType: "PAID", deliveryTime: "35-50 min", ownerId: "u2", bannerUrl: "", profileUrl: "", socialLinks: { instagram: "@capekush", whatsapp: "+27839876543" }, openNow: false, featured: false, operatingHours: { ...DEFAULT_HOURS, sun: { open: "10:00", close: "20:00", isOpen: false } }, banking: null },
];

export const PRODUCTS = [
  { id: "p1", dispensaryId: "d1", name: "Purple Haze", slug: "purple-haze", description: "A legendary sativa-dominant strain with a sweet, earthy aroma. Known for its uplifting cerebral effects.", category: "INDOOR_FLOWER", price: 160, unit: "per gram", thcPercent: 28, cbdPercent: 0.5, strainType: "SATIVA", effectSpectrum: 8, stock: 50, isActive: true },
  { id: "p2", dispensaryId: "d1", name: "OG Kush", slug: "og-kush", description: "A classic hybrid with piney, woody undertones. Delivers powerful relaxation with mild euphoria.", category: "INDOOR_FLOWER", price: 140, unit: "per gram", thcPercent: 24, cbdPercent: 1, strainType: "HYBRID", effectSpectrum: 4, stock: 35, isActive: true },
  { id: "p3", dispensaryId: "d1", name: "CBD Calm Drops", slug: "cbd-calm-drops", description: "Full-spectrum CBD oil tincture. 1000mg per 30ml bottle.", category: "CONCENTRATE", price: 450, unit: "per bottle", thcPercent: 0.3, cbdPercent: 33, strainType: "HYBRID", effectSpectrum: 1, stock: 20, isActive: true },
  { id: "p4", dispensaryId: "d1", name: "Rasta Roller Grinder", slug: "rasta-roller-grinder", description: "Premium 4-piece aluminium herb grinder with kief catcher.", category: "ACCESSORY", price: 220, unit: "per unit", thcPercent: null, cbdPercent: null, strainType: null, effectSpectrum: null, stock: 15, isActive: true },
  { id: "p5", dispensaryId: "d1", name: "Chocolate Space Cake", slug: "chocolate-space-cake", description: "Rich dark chocolate brownie infused with 50mg THC.", category: "EDIBLE", price: 120, unit: "per piece", thcPercent: 50, cbdPercent: 5, strainType: "INDICA", effectSpectrum: 2, stock: 30, isActive: true },
  { id: "p6", dispensaryId: "d2", name: "Durban Poison", slug: "durban-poison", description: "The legendary pure sativa landrace from KZN.", category: "GREENHOUSE_FLOWER", price: 120, unit: "per gram", thcPercent: 22, cbdPercent: 0.2, strainType: "SATIVA", effectSpectrum: 9, stock: 80, isActive: true },
  { id: "p7", dispensaryId: "d2", name: "Swazi Gold", slug: "swazi-gold", description: "Traditional Swazi strain grown in our Durban greenhouse.", category: "GREENHOUSE_FLOWER", price: 90, unit: "per gram", thcPercent: 18, cbdPercent: 1, strainType: "SATIVA", effectSpectrum: 7, stock: 60, isActive: true },
  { id: "p8", dispensaryId: "d3", name: "Gelato #41", slug: "gelato-41", description: "Dense, frosty buds with a sweet dessert flavour.", category: "INDOOR_FLOWER", price: 180, unit: "per gram", thcPercent: 30, cbdPercent: 0.3, strainType: "HYBRID", effectSpectrum: 5, stock: 25, isActive: true },
  { id: "p9", dispensaryId: "d3", name: "Live Resin Cartridge", slug: "live-resin-cart", description: "Full-spectrum live resin vape cart. 1g.", category: "CONCENTRATE", price: 550, unit: "per cart", thcPercent: 85, cbdPercent: 2, strainType: "HYBRID", effectSpectrum: 4, stock: 12, isActive: true },
  { id: "p10", dispensaryId: "d3", name: "Gummy Bears 10-Pack", slug: "gummy-bears", description: "Assorted fruit flavour gummies, 10mg THC each.", category: "EDIBLE", price: 200, unit: "per pack", thcPercent: 10, cbdPercent: 2, strainType: "INDICA", effectSpectrum: 3, stock: 40, isActive: true },
];

export const MOCK_USERS = [
  { id: "u1", email: "customer@test.com", phone: "+27821234567", firstName: "Thabo", lastName: "Mokoena", role: "CUSTOMER", createdAt: "2026-01-15" },
  { id: "u2", email: "dispensary@test.com", phone: "+27829876543", firstName: "Sarah", lastName: "van der Berg", role: "DISPENSARY", createdAt: "2026-01-10" },
  { id: "u3", email: "driver@test.com", phone: "+27834567890", firstName: "Sipho", lastName: "Ndlovu", role: "DRIVER", createdAt: "2026-02-01" },
  { id: "u4", email: "admin@weedeliver.co.za", phone: "+27800000001", firstName: "Admin", lastName: "User", role: "ADMIN", createdAt: "2025-12-01" },
];

export const REVENUE_DATA = [
  { day: "Mon", revenue: 4200, orders: 12 }, { day: "Tue", revenue: 5100, orders: 15 },
  { day: "Wed", revenue: 3800, orders: 11 }, { day: "Thu", revenue: 6200, orders: 18 },
  { day: "Fri", revenue: 8400, orders: 24 }, { day: "Sat", revenue: 9100, orders: 26 },
  { day: "Sun", revenue: 5500, orders: 16 },
];
